// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// distinct_failed
List distinct_failed(IntegerVector m, NumericVector failed, NumericVector censored);
RcppExport SEXP _survrec_distinct_failed(SEXP mSEXP, SEXP failedSEXP, SEXP censoredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type failed(failedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    rcpp_result_gen = Rcpp::wrap(distinct_failed(m, failed, censored));
    return rcpp_result_gen;
END_RCPP
}
// wc_fit
List wc_fit(IntegerVector m, NumericVector failed, NumericVector censored, NumericVector distinct, bool variance);
RcppExport SEXP _survrec_wc_fit(SEXP mSEXP, SEXP failedSEXP, SEXP censoredSEXP, SEXP distinctSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type failed(failedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type distinct(distinctSEXP);
    Rcpp::traits::input_parameter< bool >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(wc_fit(m, failed, censored, distinct, variance));
    return rcpp_result_gen;
END_RCPP
}
// search_seed
double search_seed(IntegerVector m, NumericVector time, IntegerVector n_event, IntegerMatrix at_risk, NumericVector lambda, double alpha_min, double alpha_max, double tol);
RcppExport SEXP _survrec_search_seed(SEXP mSEXP, SEXP timeSEXP, SEXP n_eventSEXP, SEXP at_riskSEXP, SEXP lambdaSEXP, SEXP alpha_minSEXP, SEXP alpha_maxSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_event(n_eventSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type at_risk(at_riskSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_min(alpha_minSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_max(alpha_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(search_seed(m, time, n_event, at_risk, lambda, alpha_min, alpha_max, tol));
    return rcpp_result_gen;
END_RCPP
}
// em_frailty
List em_frailty(IntegerVector m, NumericVector time, IntegerVector n_event, IntegerMatrix at_risk, NumericVector lambda, double alpha, double tol, int maxiter);
RcppExport SEXP _survrec_em_frailty(SEXP mSEXP, SEXP timeSEXP, SEXP n_eventSEXP, SEXP at_riskSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_event(n_eventSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type at_risk(at_riskSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(em_frailty(m, time, n_event, at_risk, lambda, alpha, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// mle_survival_r
NumericVector mle_survival_r(NumericVector lambda, double alpha);
RcppExport SEXP _survrec_mle_survival_r(SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(mle_survival_r(lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}
// boot_quantile
List boot_quantile(IntegerVector m, NumericVector failed, NumericVector censored, NumericVector tau, int nboot, int plan, double percentile, int nthreads);
RcppExport SEXP _survrec_boot_quantile(SEXP mSEXP, SEXP failedSEXP, SEXP censoredSEXP, SEXP tauSEXP, SEXP nbootSEXP, SEXP planSEXP, SEXP percentileSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type failed(failedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type censored(censoredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< int >::type plan(planSEXP);
    Rcpp::traits::input_parameter< double >::type percentile(percentileSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_quantile(m, failed, censored, tau, nboot, plan, percentile, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_survrec_distinct_failed", (DL_FUNC) &_survrec_distinct_failed, 3},
    {"_survrec_wc_fit", (DL_FUNC) &_survrec_wc_fit, 5},
    {"_survrec_search_seed", (DL_FUNC) &_survrec_search_seed, 8},
    {"_survrec_em_frailty", (DL_FUNC) &_survrec_em_frailty, 8},
    {"_survrec_mle_survival_r", (DL_FUNC) &_survrec_mle_survival_r, 2},
    {"_survrec_boot_quantile", (DL_FUNC) &_survrec_boot_quantile, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_survrec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
