# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.distinct_failed <- function(m, failed, censored) {
  .Call(`_survrec_distinct_failed`, m, failed, censored)
}

.wc_fit <- function(m, failed, censored, distinct, variance = TRUE) {
  .Call(`_survrec_wc_fit`, m, failed, censored, distinct, variance)
}

.search_seed <- function(m, time, n_event, at_risk, lambda, alpha_min, alpha_max, tol) {
  .Call(`_survrec_search_seed`, m, time, n_event, at_risk, lambda, alpha_min, alpha_max, tol)
}

.em_frailty <- function(m, time, n_event, at_risk, lambda, alpha, tol, maxiter) {
  .Call(`_survrec_em_frailty`, m, time, n_event, at_risk, lambda, alpha, tol, maxiter)
}

.mle_survival <- function(lambda, alpha) {
  .Call(`_survrec_mle_survival_r`, lambda, alpha)
}

.boot_quantile <- function(m, failed, censored, tau, nboot, plan, percentile, nthreads = 0L) {
  .Call(`_survrec_boot_quantile`, m, failed, censored, tau, nboot, plan, percentile, nthreads)
}
